language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.5"
      env: USE_PSALM=0
      dist: trusty
    - php: "5.6"
      env: USE_PSALM=0
    - php: "7.0"
      env: USE_PSALM=0
    - php: "7.1"
      env: USE_PSALM=1
    - php: "7.2"
      env: USE_PSALM=1
    - php: "7.3"
      env: USE_PSALM=1
    - php: "7.4"
      env: USE_PSALM=1
    - php: "8.0"
      env: USE_PSALM=1
    - php: "nightly"
      env: USE_PSALM=1
    - php: "master"
      env: USE_PSALM=1
  allow_failures:
    - php: "8.0"
    - php: "nightly"
    - php: "master"

install:
    - travis_retry composer install
    - if [[ $USE_PSALM -eq 1 ]]; then travis_retry composer require --dev "vimeo/psalm:^3"; fi

script:
    - vendor/bin/phpunit
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
